name: Docker CI/CD

on:
  push:
    branches:
      - master  # Пайплайн запускается при каждом пуше в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Выбираем операционную систему для пайплайна

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      # Шаг 4: Запуск тестов (если они добавлены в проект)
      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest tests/ --maxfail=1 --disable-warnings  # Остановка при первом провале, скрытие предупреждений


      # Шаг 5: Статический анализ безопасности кода с Bandit
      - name: Run Bandit security check
        run: |
          pip install bandit
          bandit -r .  # Рекурсивная проверка всех файлов проекта

      # Шаг 6: Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t destep/calculator-api .

      # Шаг 7: Проверка Docker-образа на уязвимости с помощью Trivy
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.8.1
        with:
          image-ref: destep/calculator-api

      # Шаг 8: Вход в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 9: Публикация Docker-образа на Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push destep/calculator-api
